# Generated by Django 6.0.5 on 2026-05-20 05:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='landcategory',
            options={'verbose_name_plural': 'Land Categories'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auction',
            name='current_highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='resolution_remarks',
            field=models.TextField(blank=True, help_text='Remarks from admin when resolving the grievance', null=True),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimum_increment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.tender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='landrecord',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tender',
            name='earnest_money_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tender',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'bidder')},
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auction_status'], name='base_auctio_auction_3866e4_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auction_start_time', 'auction_end_time'], name='base_auctio_auction_a7aac8_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['slug'], name='base_auctio_slug_99df50_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bid_status'], name='base_bid_bid_sta_bb73b3_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['-bid_amount'], name='base_bid_bid_amo_95a32e_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['submitted_at'], name='base_bid_submitt_07b2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_status'], name='base_contra_contrac_9edef6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='base_contra_start_d_719436_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='base_contra_contrac_f7b68c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='base_custom_role_7cce2d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='base_custom_is_veri_fdd46b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-created_at'], name='base_custom_created_4cc8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name'], name='base_depart_departm_19a3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['verification_status'], name='base_docume_verific_09595b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['user', 'verification_status'], name='base_docume_user_id_d86e53_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['-uploaded_at'], name='base_docume_uploade_6e5441_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status'], name='base_grieva_status_3ec767_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['user', 'status'], name='base_grieva_user_id_8f8bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['-created_at'], name='base_grieva_created_995b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='landcategory',
            index=models.Index(fields=['category_name'], name='base_landca_categor_1824b3_idx'),
        ),
        migrations.AddIndex(
            model_name='landrecord',
            index=models.Index(fields=['status'], name='base_landre_status_98d57e_idx'),
        ),
        migrations.AddIndex(
            model_name='landrecord',
            index=models.Index(fields=['district', 'state'], name='base_landre_distric_e05393_idx'),
        ),
        migrations.AddIndex(
            model_name='landrecord',
            index=models.Index(fields=['slug'], name='base_landre_slug_9e2b99_idx'),
        ),
        migrations.AddIndex(
            model_name='landrecord',
            index=models.Index(fields=['-created_at'], name='base_landre_created_722bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='base_notifi_user_id_1db9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='base_notifi_notific_39da70_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='base_notifi_created_929dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='base_paymen_payment_283e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='base_paymen_payment_90ed8d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='base_paymen_transac_4b4337_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='base_paymen_payment_3ea2de_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['tender_status'], name='base_tender_tender__da5089_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['start_date', 'end_date'], name='base_tender_start_d_0babde_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['slug'], name='base_tender_slug_4e49c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['-created_at'], name='base_tender_created_ca4533_idx'),
        ),
    ]
