# Generated by Django 6.0.5 on 2026-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
