# Generated by Django 6.0.5 on 2026-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_auction_current_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='resolution_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
